import os
import json
import base64
import io
from flask import Flask, render_template, request, jsonify
from dotenv import load_dotenv
from PIL import Image
import google.generativeai as genai

# Load environment variables
load_dotenv()

app = Flask(__name__)
app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024  # 16MB max file size

# Configure Gemini API
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
if not GOOGLE_API_KEY:
    print("WARNING: GOOGLE_API_KEY not found in .env file")
else:
    genai.configure(api_key=GOOGLE_API_KEY)

# Load catalog
with open('catalog.json', 'r') as f:
    catalog_data = json.load(f)

@app.route('/')
def index():
    """Render the main page"""
    return render_template('index.html')

@app.route('/catalog')
def get_catalog():
    """Get catalog items"""
    return jsonify(catalog_data)

@app.route('/try-on', methods=['POST'])
def try_on():
    """
    Handle virtual try-on request
    Expects: user_image (base64), item_id
    Returns: generated image as base64
    """
    try:
        # Get request data
        data = request.get_json()

        if not data:
            return jsonify({'error': 'No data provided'}), 400

        user_image_b64 = data.get('user_image')
        item_id = data.get('item_id')

        if not user_image_b64 or not item_id:
            return jsonify({'error': 'Missing user_image or item_id'}), 400

        # Find item in catalog
        item = next((i for i in catalog_data['items'] if i['id'] == item_id), None)
        if not item:
            return jsonify({'error': f'Item {item_id} not found in catalog'}), 404

        print(f"Processing try-on for item: {item['name']}")

        # Decode user image from base64
        if ',' in user_image_b64:
            user_image_b64 = user_image_b64.split(',')[1]

        user_image_bytes = base64.b64decode(user_image_b64)
        user_img = Image.open(io.BytesIO(user_image_bytes))

        # Load garment image
        garment_path = os.path.join('static', item['image'])
        if not os.path.exists(garment_path):
            return jsonify({'error': f'Garment image not found: {garment_path}'}), 404

        garment_img = Image.open(garment_path)

        # Check if API key is configured
        if not GOOGLE_API_KEY:
            return jsonify({'error': 'GOOGLE_API_KEY not configured. Please add it to your .env file'}), 500

        # Construct prompt for Gemini
        prompt = f"""You are a virtual try-on assistant. Your task is to show how a person would look wearing a specific garment.

INSTRUCTIONS:
1. Take the person from the first image (their face, hair, body, pose, skin tone)
2. Take the garment from the second image
3. Generate a new image showing this exact person wearing this exact garment
4. The result should look natural and photorealistic
5. Preserve the person's identity perfectly - same face, same hair, same skin tone
6. The garment should fit naturally on their body

GARMENT DETAILS:
{item['prompt']}

Generate the try-on image now."""

        print("Calling Gemini API...")

        # Call Gemini API
        model = genai.GenerativeModel("gemini-2.0-flash-exp")

        response = model.generate_content(
            [prompt, user_img, garment_img],
            generation_config=genai.GenerationConfig(
                response_modalities=["image"]
            )
        )

        print("Gemini API response received")

        # Extract generated image from response
        generated_image_b64 = None

        if hasattr(response, 'candidates') and response.candidates:
            for part in response.candidates[0].content.parts:
                if hasattr(part, 'inline_data') and part.inline_data:
                    image_data = part.inline_data.data
                    # Convert to base64 if it's bytes
                    if isinstance(image_data, bytes):
                        generated_image_b64 = base64.b64encode(image_data).decode('utf-8')
                    else:
                        generated_image_b64 = image_data
                    break

        if not generated_image_b64:
            print("No image found in response")
            return jsonify({'error': 'No image generated by the model. The API may have returned text only or encountered an error.'}), 500

        print("Successfully generated try-on image")

        return jsonify({
            'success': True,
            'generated_image': f'data:image/jpeg;base64,{generated_image_b64}',
            'item_name': item['name']
        })

    except Exception as e:
        print(f"Error in try-on: {str(e)}")
        import traceback
        traceback.print_exc()
        return jsonify({'error': f'Server error: {str(e)}'}), 500

if __name__ == '__main__':
    # Check if .env exists
    if not os.path.exists('.env'):
        print("\n⚠️  WARNING: .env file not found!")
        print("Please create a .env file with your GOOGLE_API_KEY")
        print("You can copy .env.example to .env and add your API key\n")

    app.run(debug=True, host='0.0.0.0', port=5000)
