import os
import json
import base64
import io
from flask import Flask, render_template, request, jsonify
from dotenv import load_dotenv
from PIL import Image

# Original Google GenAI SDK
import google.generativeai as genai

# Load environment variables
load_dotenv()

app = Flask(__name__)
app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024  # 16MB max file size

# Configure Gemini API
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
if not GOOGLE_API_KEY:
    print("WARNING: GOOGLE_API_KEY not found in .env file")
else:
    genai.configure(api_key=GOOGLE_API_KEY)

# Load catalog
with open('catalog.json', 'r') as f:
    catalog_data = json.load(f)


def pil_to_bytes(pil_image):
    """Convert PIL Image to bytes"""
    buffer = io.BytesIO()
    pil_image.save(buffer, format='PNG')
    return buffer.getvalue()


def decode_base64_image(image_b64):
    """Decode base64 image to PIL Image"""
    if ',' in image_b64:
        image_b64 = image_b64.split(',')[1]
    image_bytes = base64.b64decode(image_b64)
    return Image.open(io.BytesIO(image_bytes))


@app.route('/')
def index():
    """Render the main page"""
    return render_template('index.html')


@app.route('/playground')
def playground():
    """Render the playground page for direct prompting"""
    return render_template('playground.html')


@app.route('/catalog')
def get_catalog():
    """Get catalog items"""
    return jsonify(catalog_data)


@app.route('/try-on', methods=['POST'])
def try_on():
    """
    Handle virtual try-on request
    Expects: user_image (base64), item_id
    Returns: generated image as base64
    """
    try:
        data = request.get_json()

        if not data:
            return jsonify({'error': 'No data provided'}), 400

        user_image_b64 = data.get('user_image')
        item_id = data.get('item_id')

        if not user_image_b64 or not item_id:
            return jsonify({'error': 'Missing user_image or item_id'}), 400

        # Find item in catalog
        item = next((i for i in catalog_data['items'] if i['id'] == item_id), None)
        if not item:
            return jsonify({'error': f'Item {item_id} not found in catalog'}), 404

        print(f"Processing try-on for item: {item['name']}")

        # Check if API key is configured
        if not GOOGLE_API_KEY:
            return jsonify({'error': 'GOOGLE_API_KEY not configured. Please add it to your .env file'}), 500

        # Decode user image
        user_img = decode_base64_image(user_image_b64)

        # Load garment image
        garment_path = os.path.join('static', item['image'])
        if not os.path.exists(garment_path):
            return jsonify({'error': f'Garment image not found: {garment_path}'}), 404

        garment_img = Image.open(garment_path)

        # Construct prompt for Gemini
        prompt = f"""You are a virtual try-on assistant. Your task is to show how a person would look wearing a specific garment.

INSTRUCTIONS:
1. Take the person from the first image (their face, hair, body, pose, skin tone)
2. Take the garment from the second image
3. Generate a new image showing this exact person wearing this exact garment
4. The result should look natural and photorealistic
5. Preserve the person's identity perfectly - same face, same hair, same skin tone
6. The garment should fit naturally on their body

GARMENT DETAILS:
{item['prompt']}

Generate the try-on image now."""

        print("Calling Gemini API...")

        # Create model and generate content
        model = genai.GenerativeModel("gemini-2.0-flash-exp-image-generation")

        response = model.generate_content(
            [prompt, user_img, garment_img],
            generation_config=genai.GenerationConfig(
                response_mime_type="text/plain"
            )
        )

        print("Gemini API response received")

        # Extract generated image from response
        generated_image_b64 = None

        if response.candidates and response.candidates[0].content.parts:
            for part in response.candidates[0].content.parts:
                if hasattr(part, 'inline_data') and part.inline_data:
                    image_data = part.inline_data.data
                    if isinstance(image_data, bytes):
                        generated_image_b64 = base64.b64encode(image_data).decode('utf-8')
                    else:
                        generated_image_b64 = image_data
                    break

        if not generated_image_b64:
            print("No image found in response")
            return jsonify({'error': 'No image generated by the model.'}), 500

        print("Successfully generated try-on image")

        return jsonify({
            'success': True,
            'generated_image': f'data:image/jpeg;base64,{generated_image_b64}',
            'item_name': item['name']
        })

    except Exception as e:
        print(f"Error in try-on: {str(e)}")
        import traceback
        traceback.print_exc()
        return jsonify({'error': f'Server error: {str(e)}'}), 500


def build_mode_prompt(mode, user_prompt):
    """Build the appropriate prompt based on the generation mode"""
    mode_prompts = {
        'text-to-image': user_prompt,

        'image-editing': f"""You are an image editing assistant. Your task is to modify the provided image according to the user's instructions.

INSTRUCTIONS:
{user_prompt}

Apply the requested changes to the image while preserving the overall composition and quality. Make the edits look natural and seamless.""",

        'style-transfer': f"""You are a style transfer assistant. Your task is to apply the artistic style from the style reference image to the content image.

INSTRUCTIONS:
{user_prompt}

The first image is the content to preserve. The second image is the style reference.
Apply the artistic style (colors, textures, brush strokes, artistic techniques) from the style reference to the content image while preserving the structure and subjects of the content image.""",

        'inpainting': f"""You are an image inpainting assistant. Your task is to fill in or replace the masked area of the image.

The image has a mask where white areas indicate regions to be modified/filled and black areas should be preserved.

INSTRUCTIONS:
{user_prompt}

Fill the masked area with content that:
1. Matches the user's description
2. Blends seamlessly with the surrounding image
3. Maintains consistent lighting, perspective, and style""",

        'outpainting': f"""You are an image outpainting assistant. Your task is to extend the image beyond its original boundaries.

The mask indicates the new area to generate (white) while preserving the original image (black).

INSTRUCTIONS:
{user_prompt}

Extend the image by:
1. Generating content that logically continues the scene
2. Matching the style, lighting, and perspective of the original
3. Creating a seamless transition between original and new content"""
    }

    return mode_prompts.get(mode, user_prompt)


@app.route('/generate', methods=['POST'])
def generate():
    """
    Handle direct image generation request
    Supports multiple modes: text-to-image, image-editing, style-transfer, inpainting, outpainting
    """
    try:
        data = request.get_json()

        if not data:
            return jsonify({'error': 'No data provided'}), 400

        user_prompt = data.get('prompt')
        mode = data.get('mode', 'text-to-image')
        image_b64 = data.get('image')  # Source image
        mask_b64 = data.get('mask')  # Mask for inpainting/outpainting
        style_b64 = data.get('style_image')  # Style reference for style transfer

        # Settings (kept for UI compatibility, but may not all be supported by the model)
        model_name = data.get('model', 'gemini-2.0-flash-exp-image-generation')

        if not user_prompt:
            return jsonify({'error': 'Missing prompt'}), 400

        print(f"Processing {mode} request with prompt: {user_prompt[:100]}...")
        print(f"Settings: model={model_name}")

        # Check if API key is configured
        if not GOOGLE_API_KEY:
            return jsonify({'error': 'GOOGLE_API_KEY not configured. Please add it to your .env file'}), 500

        # Build the mode-specific prompt
        prompt = build_mode_prompt(mode, user_prompt)

        # Build content list
        contents = [prompt]

        # Add images based on mode
        if mode == 'text-to-image':
            if image_b64:
                img = decode_base64_image(image_b64)
                contents.append(img)

        elif mode == 'image-editing':
            if not image_b64:
                return jsonify({'error': 'Source image required for image editing mode'}), 400
            img = decode_base64_image(image_b64)
            contents.append(img)

        elif mode == 'style-transfer':
            if not image_b64:
                return jsonify({'error': 'Content image required for style transfer mode'}), 400
            if not style_b64:
                return jsonify({'error': 'Style reference image required for style transfer mode'}), 400
            content_img = decode_base64_image(image_b64)
            style_img = decode_base64_image(style_b64)
            contents.append(content_img)
            contents.append(style_img)

        elif mode in ['inpainting', 'outpainting']:
            if not image_b64:
                return jsonify({'error': f'Source image required for {mode} mode'}), 400
            if not mask_b64:
                return jsonify({'error': f'Mask image required for {mode} mode'}), 400
            source_img = decode_base64_image(image_b64)
            mask_img = decode_base64_image(mask_b64)
            contents.append(source_img)
            contents.append(mask_img)

        print("Calling Gemini API...")

        # Create model
        model = genai.GenerativeModel(model_name)

        # Generate content
        response = model.generate_content(
            contents,
            generation_config=genai.GenerationConfig(
                response_mime_type="text/plain"
            )
        )

        print("Gemini API response received")

        # Extract generated image from response
        generated_image_b64 = None
        response_text = None

        if response.candidates and response.candidates[0].content.parts:
            for part in response.candidates[0].content.parts:
                if hasattr(part, 'inline_data') and part.inline_data:
                    image_data = part.inline_data.data
                    if isinstance(image_data, bytes):
                        generated_image_b64 = base64.b64encode(image_data).decode('utf-8')
                    else:
                        generated_image_b64 = image_data
                elif hasattr(part, 'text') and part.text:
                    response_text = part.text

        if not generated_image_b64:
            error_msg = 'No image generated by the model.'
            if response_text:
                error_msg += f' Model response: {response_text}'
            print(error_msg)
            return jsonify({'error': error_msg}), 500

        print(f"Successfully generated image using {mode} mode")

        return jsonify({
            'success': True,
            'generated_image': f'data:image/jpeg;base64,{generated_image_b64}',
            'mode': mode
        })

    except Exception as e:
        print(f"Error in generate: {str(e)}")
        import traceback
        traceback.print_exc()
        return jsonify({'error': f'Server error: {str(e)}'}), 500


if __name__ == '__main__':
    # Check if .env exists
    if not os.path.exists('.env'):
        print("\nWARNING: .env file not found!")
        print("Please create a .env file with your GOOGLE_API_KEY")
        print("You can copy .env.example to .env and add your API key\n")

    app.run(debug=True, host='0.0.0.0', port=5000)
